### ISSUE TITLE
How to setup tests for non tenant pages.

### ISSUE THREAD

**Issue by Draqun** [django-tenants/django-tenants#1139]
Hi. I decided to switch from the django-tenant-schemas package to django-tenants, and while this went quite smoothly, I can't get the tests to run, and I care a lot about this due to the fact that regression errors are popping up every now and then.

I uses the following packages
```toml
[tool.poetry.dependencies]
python = "^3.13"
django = "~5.1.8"
django-tenants = "^3.7.0"
dj-database-url = "^2.3.0"
django-bootstrap5 = "^24.3"
django-bootstrap-icons = "^0.9.0"
uvicorn = "^0.34.0"
uvicorn-worker = "^0.2.0"
gunicorn = "^23.0.0"
whitenoise = "^6.8.2"
encrypt-decrypt-fields = "^1.3.6"
django-bootstrap-modal-forms = "^3.0.5"
django-model-utils = "^5.0.0"
werkzeug = "^3.1.3"
tzdata = "^2024.2"
pytz = "^2024.2"
psycopg = {extras = ["binary", "pool"], version = "^3.2.4"}
django-colorfield = "^0.12.0"
sentry-sdk = {extras = ["django"], version = "^2.25.1"}
```

An example test looks like this
```python
# External Dependencies
from django.conf import settings
from django.urls import reverse_lazy
from django.utils import translation
from django_tenants.test.cases import TenantTestCase
from django_tenants.test.client import TenantClient


class ContactViewTests(TenantTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.client = TenantClient(self.tenant)
        self.client.cookies.load({settings.LANGUAGE_COOKIE_NAME: "pl"})

    def test_contact_view_is_loaded(self):
        with translation.override("pl"):
            response = self.client.get(reverse_lazy("common:contact"))
        self.assertEqual(200, response.status_code)
        self.assertContains(response, "Kontakt")
```

Part of the stacktrace looks like this
```
    raise MigrationSchemaMissing(
        "Unable to create the django_migrations table (%s)" % exc
    )
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (no schema has been selected to create in
LINE 1: CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMA...
                     ^)
```

During debugging I discover there was the following exception: `AttributeError: "MigrationRecorder" object has no attribute "recorder"`

Where I should setup schema to make test works?
Best regards.

EDIT:
It turns out that the transition from django-tenant-schemas to django-tenants has not gone well. Unfortunately, running the migration on an empty database also ends with an error. Migrations in the tenant application do not execute. The problem is therefore not located in the configuration.
